/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NutritionIndexRouteImport } from './routes/nutrition/index'
import { Route as ProgressIndexRouteImport } from './routes/progress/index'
import { Route as ReviewIndexRouteImport } from './routes/review/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as WorkoutIndexRouteImport } from './routes/workout/index'
import { Route as NutritionPlanningIndexRouteImport } from './routes/nutrition/planning/index'
import { Route as NutritionTemplatesIndexRouteImport } from './routes/nutrition/templates/index'
import { Route as NutritionTemplatesTemplateIdRouteImport } from './routes/nutrition/templates/$templateId'
import { Route as WorkoutProgramsIndexRouteImport } from './routes/workout/programs/index'
import { Route as WorkoutProgramsProgramIdRouteImport } from './routes/workout/programs/$programId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionIndexRoute = NutritionIndexRouteImport.update({
  id: '/nutrition/',
  path: '/nutrition/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressIndexRoute = ProgressIndexRouteImport.update({
  id: '/progress/',
  path: '/progress/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutIndexRoute = WorkoutIndexRouteImport.update({
  id: '/workout/',
  path: '/workout/',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionPlanningIndexRoute = NutritionPlanningIndexRouteImport.update({
  id: '/nutrition/planning/',
  path: '/nutrition/planning/',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionTemplatesIndexRoute = NutritionTemplatesIndexRouteImport.update({
  id: '/nutrition/templates/',
  path: '/nutrition/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionTemplatesTemplateIdRoute =
  NutritionTemplatesTemplateIdRouteImport.update({
    id: '/nutrition/templates/$templateId',
    path: '/nutrition/templates/$templateId',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkoutProgramsIndexRoute = WorkoutProgramsIndexRouteImport.update({
  id: '/workout/programs/',
  path: '/workout/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutProgramsProgramIdRoute =
  WorkoutProgramsProgramIdRouteImport.update({
    id: '/workout/programs/$programId',
    path: '/workout/programs/$programId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nutrition/': typeof NutritionIndexRoute
  '/progress/': typeof ProgressIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/workout/': typeof WorkoutIndexRoute
  '/nutrition/templates/$templateId': typeof NutritionTemplatesTemplateIdRoute
  '/workout/programs/$programId': typeof WorkoutProgramsProgramIdRoute
  '/nutrition/planning/': typeof NutritionPlanningIndexRoute
  '/nutrition/templates/': typeof NutritionTemplatesIndexRoute
  '/workout/programs/': typeof WorkoutProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nutrition': typeof NutritionIndexRoute
  '/progress': typeof ProgressIndexRoute
  '/review': typeof ReviewIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/workout': typeof WorkoutIndexRoute
  '/nutrition/templates/$templateId': typeof NutritionTemplatesTemplateIdRoute
  '/workout/programs/$programId': typeof WorkoutProgramsProgramIdRoute
  '/nutrition/planning': typeof NutritionPlanningIndexRoute
  '/nutrition/templates': typeof NutritionTemplatesIndexRoute
  '/workout/programs': typeof WorkoutProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nutrition/': typeof NutritionIndexRoute
  '/progress/': typeof ProgressIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/workout/': typeof WorkoutIndexRoute
  '/nutrition/templates/$templateId': typeof NutritionTemplatesTemplateIdRoute
  '/workout/programs/$programId': typeof WorkoutProgramsProgramIdRoute
  '/nutrition/planning/': typeof NutritionPlanningIndexRoute
  '/nutrition/templates/': typeof NutritionTemplatesIndexRoute
  '/workout/programs/': typeof WorkoutProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/nutrition/'
    | '/progress/'
    | '/review/'
    | '/settings/'
    | '/workout/'
    | '/nutrition/templates/$templateId'
    | '/workout/programs/$programId'
    | '/nutrition/planning/'
    | '/nutrition/templates/'
    | '/workout/programs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/nutrition'
    | '/progress'
    | '/review'
    | '/settings'
    | '/workout'
    | '/nutrition/templates/$templateId'
    | '/workout/programs/$programId'
    | '/nutrition/planning'
    | '/nutrition/templates'
    | '/workout/programs'
  id:
    | '__root__'
    | '/'
    | '/nutrition/'
    | '/progress/'
    | '/review/'
    | '/settings/'
    | '/workout/'
    | '/nutrition/templates/$templateId'
    | '/workout/programs/$programId'
    | '/nutrition/planning/'
    | '/nutrition/templates/'
    | '/workout/programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NutritionIndexRoute: typeof NutritionIndexRoute
  ProgressIndexRoute: typeof ProgressIndexRoute
  ReviewIndexRoute: typeof ReviewIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  WorkoutIndexRoute: typeof WorkoutIndexRoute
  NutritionTemplatesTemplateIdRoute: typeof NutritionTemplatesTemplateIdRoute
  WorkoutProgramsProgramIdRoute: typeof WorkoutProgramsProgramIdRoute
  NutritionPlanningIndexRoute: typeof NutritionPlanningIndexRoute
  NutritionTemplatesIndexRoute: typeof NutritionTemplatesIndexRoute
  WorkoutProgramsIndexRoute: typeof WorkoutProgramsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition/': {
      id: '/nutrition/'
      path: '/nutrition'
      fullPath: '/nutrition/'
      preLoaderRoute: typeof NutritionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/': {
      id: '/progress/'
      path: '/progress'
      fullPath: '/progress/'
      preLoaderRoute: typeof ProgressIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/': {
      id: '/review/'
      path: '/review'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/': {
      id: '/workout/'
      path: '/workout'
      fullPath: '/workout/'
      preLoaderRoute: typeof WorkoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition/planning/': {
      id: '/nutrition/planning/'
      path: '/nutrition/planning'
      fullPath: '/nutrition/planning/'
      preLoaderRoute: typeof NutritionPlanningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition/templates/': {
      id: '/nutrition/templates/'
      path: '/nutrition/templates'
      fullPath: '/nutrition/templates/'
      preLoaderRoute: typeof NutritionTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition/templates/$templateId': {
      id: '/nutrition/templates/$templateId'
      path: '/nutrition/templates/$templateId'
      fullPath: '/nutrition/templates/$templateId'
      preLoaderRoute: typeof NutritionTemplatesTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/programs/': {
      id: '/workout/programs/'
      path: '/workout/programs'
      fullPath: '/workout/programs/'
      preLoaderRoute: typeof WorkoutProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/programs/$programId': {
      id: '/workout/programs/$programId'
      path: '/workout/programs/$programId'
      fullPath: '/workout/programs/$programId'
      preLoaderRoute: typeof WorkoutProgramsProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NutritionIndexRoute: NutritionIndexRoute,
  ProgressIndexRoute: ProgressIndexRoute,
  ReviewIndexRoute: ReviewIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  WorkoutIndexRoute: WorkoutIndexRoute,
  NutritionTemplatesTemplateIdRoute: NutritionTemplatesTemplateIdRoute,
  WorkoutProgramsProgramIdRoute: WorkoutProgramsProgramIdRoute,
  NutritionPlanningIndexRoute: NutritionPlanningIndexRoute,
  NutritionTemplatesIndexRoute: NutritionTemplatesIndexRoute,
  WorkoutProgramsIndexRoute: WorkoutProgramsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
